### PR TITLE
Update to latest mathlib

### PR DESCRIPTION
**Pull request by mseri**

### CODE REVIEW

**Comment by mseri** [comment]
A number of changes in the API require changes in our code

**Comment by mseri** [comment]
@pitmonticone are you familiar with the necessary changes?

**Comment by pitmonticone** [comment]
I'm going to partially fix it soon. I believe I need to `sorry` at least one `have`.

**Comment by pitmonticone** [comment]
For mathlib-level quality code we should redesign the section variables as prescribed by the linter.

**Comment by pitmonticone** [comment]
Now it builds correctly. It requires a few more tinkering though.

**Comment by mseri** [comment]
Thanks a lot! I'll merge the current version, we can tinker with separate PRs

**Pull request merged**
